### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
There is just too many errors to salvage...

https://gitlab.com/construo/construo/-/issues/1

**Comment by hfiguiere** [comment]
it probably just miss a few includes

**Comment by bbhtt** [comment]
The issue is some of them are submodules inside the project folder which I can't update https://gitlab.com/construo/construo/-/tree/master/external?ref_type=heads

And upstream changed the build by adding more submodules like tinycmmc so I can't update the commit of the app as well.

**Comment by hfiguiere** [comment]
patches, patches, patches

**Comment by hfiguiere** [comment]
Actually all you need is this patch:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ea94301..658294f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -217,7 +217,7 @@ set_target_properties(libconstruo PROPERTIES
   CXX_STANDARD_REQUIRED ON
   CXX_EXTENSIONS OFF)
 set_target_properties(libconstruo PROPERTIES OUTPUT_NAME construo)
-target_compile_options(libconstruo PRIVATE -std=c++11)
+# target_compile_options(libconstruo PRIVATE -std=c++11)
 target_link_libraries(libconstruo PUBLIC prio)
 
 if(GLUT_FOUND AND OPENGL_FOUND)
```

**Comment by bbhtt** [comment]
Indeed, thanks. Feel free to push

**Comment by hfiguiere** [comment]
you didn't add the patch, so it still fails.

**Pull request merged**
